extends Node

const DIRT_TILE_IDS = [1, 2]
const EMPTY_DIRT_TILE_ID = 0

const SCREEN_SIZE = Vector2(720, 480)
const TILE_SIZE = 8

const GROUND_LAYER = 14 * TILE_SIZE
const ENEMY_SCATTER_SPEED = 100
const ENEMY_EMERGE_SPEED = 300

const ENEMY_SPEED = 20
const ENEMY_SPAWN_RATE = 1.0
const LEVEL_TIME = 10
